version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "docker"
    directory: "/agent"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "npm"
    directory: "/agent"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
