version: '3.9'

services:
  docker-deploy-agent:
    build: .
    restart: always
    image: ${DOCKER_AGENT_IMAGE}:${DOCKER_AGENT_TAG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env